# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Season 2014"
email: "devfest@gdgvietnam.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "http://devfest.gdgvietnam.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "devfest.gdgvietnam.com"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Vietnam"
organizerAlternateName: "Google Developer Group Vietnam"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "organizer@gdgvietnam.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgvietnam.com"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, vietnam"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "September - November, 2014"
typeoutTextValues: '"", "Season", "Vietnam"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://docs.google.com/forms/d/1LCPe1whxMq7x0T9qIxeza11WGl8DZYrL4QXF3OWH9Qs/viewform", text: "REGISTER NOW"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Air Lounge"
eventLocationLink: "http://www.foody.vn/ho-chi-minh/air-lounge-coffee"
eventStreetAddress: "147 Tôn Dật Tiên, Phường Tân Phong, Quận 7, TP.HCM"
eventAddressLocality: "Hochiminh"
eventAddressLocalityRegion: "Hochiminh"
eventPostalCode: "79000"
eventAddressCountry: "Vietnam"
eventStartTime: "2014-12-06T08:00"
eventDoorTime: "08:00"
eventEndTime: "2014-12-06T21:30"
eventPlaceCoordinates: "10.723466, 106.715754"
mapCenterCoordinates: "10.723466, 106.715754"
mapMobileCenterCoordinates: "10.723466, 106.715754"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/b/106004400398954649440/", icon: "google-plus"}
 - {link: "https://www.facebook.com/gdgviet", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgvietnam.com", text: "Gdgvietnam.com"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:organizer@gdgvietnam.org", text: "organizer@gdgvietnam.org"}
